# -*- coding: utf-8 -*-
"""RAIZEN

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1qYUDvdrqvxhJ82CwsEXzOTnl1StoRpZ5
"""

 -q gradio torch torchvision huggingface_hub opencv-python-headless

import os, glob
import torch
import torch.nn as nn
import gradio as gr
import numpy as np

from PIL import Image
from torchvision.models import efficientnet_b4
from torchvision import transforms
from huggingface_hub import snapshot_download

print("🚀 RETINAGUARD starting...")

# MODEL
repo = "lebiraja/retinal-disease-classifier"
model_dir = snapshot_download(repo_id=repo)

files = []
for root, dirs, names in os.walk(model_dir):
    for name in names:
        if name.endswith((".pth",".pt",".bin",".ckpt")):
            files.append(os.path.join(root,name))

print("Model files:", files)

if not files:
    raise FileNotFoundError("Model checkpoint not found")

model = efficientnet_b4(weights=None)
model.classifier[1] = nn.Linear(
    model.classifier[1].in_features, 45
)

checkpoint = torch.load(files[0], map_location="cpu")

if isinstance(checkpoint, dict):
    if "model_state_dict" in checkpoint:
        checkpoint = checkpoint["model_state_dict"]
    elif "state_dict" in checkpoint:
        checkpoint = checkpoint["state_dict"]

checkpoint = {
    k.replace("module.","").replace("model.",""): v
    for k,v in checkpoint.items()
}

model.load_state_dict(checkpoint, strict=False)
model.eval()

print("✅ AI model loaded!")

# LABELS
labels = [
"Diabetic Retinopathy","Age-Related Macular Degeneration","Media Haze",
"Drusen","Myopia","Branch Retinal Vein Occlusion","Tessellation",
"Epiretinal Membrane","Laser Scar","Macular Scar",
"Central Serous Retinopathy","Optic Disc Cupping",
"Central Retinal Vein Occlusion","Tortuous Vessels","Asteroid Hyalosis",
"Optic Disc Pallor","Optic Disc Edema","Shunt",
"Anterior Ischemic Optic Neuropathy","Parafoveal Telangiectasia",
"Retinal Traction","Retinitis","Chorioretinitis","Exudation",
"Retinal Pigment Epithelium Changes","Macular Hole","Retinitis Pigmentosa",
"Cotton Wool Spots","Coloboma","Optic Disc Pit Maculopathy",
"Preretinal Hemorrhage","Myelinated Nerve Fibers","Hemorrhagic Retinopathy",
"Central Retinal Artery Occlusion","Tilted Disc","Cystoid Macular Edema",
"Post-Traumatic Choroidal Rupture","Choroidal Folds","Vitreous Hemorrhage",
"Macroaneurysm","Vasculitis","Branch Retinal Artery Occlusion",
"Plaque","Hemorrhagic Pigment Epithelial Detachment","Collateral"
]

transform = transforms.Compose([
    transforms.Resize((384,384)),
    transforms.ToTensor(),
    transforms.Normalize(
        [0.485,0.456,0.406],
        [0.229,0.224,0.225]
    )
])

def predict(image):

    if image is None:
        return "⚠️ Upload a retinal image."

    image = image.convert("RGB")
    x = transform(image).unsqueeze(0)

    with torch.no_grad():
        p = torch.sigmoid(model(x))[0]

    values, indices = torch.topk(p,5)

    text = "# 🧠 RETINAGUARD Result\n\n"

    for value,index in zip(values,indices):
        text += f"### {labels[int(index)]}\n"
        text += f"Probability: **{value.item()*100:.2f}%**\n\n"

    text += """
---
⚠️ This is an AI screening aid, not a medical diagnosis.
Please consult a qualified eye-care professional.
"""

    return text

# WEB PAGE
with gr.Blocks(title="RETINAGUARD") as app:

    gr.Markdown("""
# 👁️ RETINAGUARD
### Explainable AI for Rural Retinal Screening

**Retinal Image → AI Screening → Result**

---
""")

    with gr.Row():

        with gr.Column():

            image = gr.Image(
                sources=["upload","webcam"],
                type="pil",
                label="📷 Retinal / Fundus Image"
            )

            button = gr.Button(
                "🔍 Start AI Screening",
                variant="primary"
            )

        with gr.Column():

            output = gr.Markdown(
                "Upload an image to begin screening."
            )

    button.click(
        predict,
        inputs=image,
        outputs=output
    )

    gr.Markdown("""
---
### ⚠️ Medical Notice
RETINAGUARD is an AI screening aid and does not replace
professional eye examination.
""")

print("🚀 Launching web page...")

app.launch(share=True)

# ============================================================
# RETINAGUARD
# Explainable AI for Rural Retinal Screening
# COMPLETE ONE-CELL VERSION
# ============================================================
 

import os
import glob
import torch
import torch.nn as nn
import torch.nn.functional as F
import gradio as gr
import numpy as np

from PIL import Image
from torchvision.models import efficientnet_b4
from torchvision import transforms
from huggingface_hub import snapshot_download


# ============================================================
# 1. START
# ============================================================

print("==========================================")
print("      RETINAGUARD STARTING")
print("==========================================")

DEVICE = "cuda" if torch.cuda.is_available() else "cpu"

print("Device:", DEVICE)


# ============================================================
# 2. DOWNLOAD RETINAL MODEL
# ============================================================

REPO_ID = "lebiraja/retinal-disease-classifier"

print("\n📥 Downloading retinal AI model...")

MODEL_DIR = snapshot_download(
    repo_id=REPO_ID
)

print("✅ Model downloaded")


# ============================================================
# 3. FIND CHECKPOINT
# ============================================================

checkpoint_files = []

for root, dirs, files in os.walk(MODEL_DIR):

    for file in files:

        if file.lower().endswith(
            (".pth", ".pt", ".bin", ".ckpt")
        ):

            checkpoint_files.append(
                os.path.join(root, file)
            )

print("\n📦 Checkpoint files found:")

for file in checkpoint_files:
    print(file)

if not checkpoint_files:

    raise FileNotFoundError(
        "❌ No model checkpoint found."
    )

checkpoint_path = checkpoint_files[0]

print("\nUsing checkpoint:")
print(checkpoint_path)


# ============================================================
# 4. CREATE EFFICIENTNET-B4
# ============================================================

print("\n🧠 Loading AI architecture...")

model = efficientnet_b4(
    weights=None
)

model.classifier[1] = nn.Linear(
    model.classifier[1].in_features,
    45
)


# ============================================================
# 5. LOAD CHECKPOINT
# ============================================================

checkpoint = torch.load(
    checkpoint_path,
    map_location="cpu"
)

if isinstance(checkpoint, dict):

    if "model_state_dict" in checkpoint:

        state_dict = checkpoint["model_state_dict"]

    elif "state_dict" in checkpoint:

        state_dict = checkpoint["state_dict"]

    else:

        state_dict = checkpoint

else:

    state_dict = checkpoint


clean_state_dict = {}

for key, value in state_dict.items():

    key = key.replace("module.", "")
    key = key.replace("model.", "")
    key = key.replace("net.", "")

    clean_state_dict[key] = value


missing, unexpected = model.load_state_dict(
    clean_state_dict,
    strict=False
)

model = model.to(DEVICE)
model.eval()

print("\n✅ RETINAGUARD AI MODEL LOADED")
print("Output classes:", 45)
print("Missing keys:", len(missing))
print("Unexpected keys:", len(unexpected))


# ============================================================
# 6. 45 RETINAL CONDITIONS
# ============================================================

disease_labels = [

    "Diabetic Retinopathy",
    "Age-Related Macular Degeneration",
    "Media Haze",
    "Drusen",
    "Myopia",
    "Branch Retinal Vein Occlusion",
    "Tessellation",
    "Epiretinal Membrane",
    "Laser Scar",
    "Macular Scar",
    "Central Serous Retinopathy",
    "Optic Disc Cupping",
    "Central Retinal Vein Occlusion",
    "Tortuous Vessels",
    "Asteroid Hyalosis",
    "Optic Disc Pallor",
    "Optic Disc Edema",
    "Shunt",
    "Anterior Ischemic Optic Neuropathy",
    "Parafoveal Telangiectasia",
    "Retinal Traction",
    "Retinitis",
    "Chorioretinitis",
    "Exudation",
    "Retinal Pigment Epithelium Changes",
    "Macular Hole",
    "Retinitis Pigmentosa",
    "Cotton Wool Spots",
    "Coloboma",
    "Optic Disc Pit Maculopathy",
    "Preretinal Hemorrhage",
    "Myelinated Nerve Fibers",
    "Hemorrhagic Retinopathy",
    "Central Retinal Artery Occlusion",
    "Tilted Disc",
    "Cystoid Macular Edema",
    "Post-Traumatic Choroidal Rupture",
    "Choroidal Folds",
    "Vitreous Hemorrhage",
    "Macroaneurysm",
    "Vasculitis",
    "Branch Retinal Artery Occlusion",
    "Plaque",
    "Hemorrhagic Pigment Epithelial Detachment",
    "Collateral"
]


# ============================================================
# 7. IMAGE TRANSFORM
# ============================================================

transform = transforms.Compose([

    transforms.Resize(
        (384, 384)
    ),

    transforms.ToTensor(),

    transforms.Normalize(

        mean=[
            0.485,
            0.456,
            0.406
        ],

        std=[
            0.229,
            0.224,
            0.225
        ]
    )
])


# ============================================================
# 8. GLOBAL SESSION DATA
# ============================================================

session_results = []
patient_data = {}


# ============================================================
# 9. AI PREDICTION
# ============================================================

def predict_retina(image):

    global session_results

    if image is None:

        return (
            "⚠️ Please upload or capture a retinal image."
        )

    image = image.convert("RGB")

    tensor = transform(
        image
    ).unsqueeze(0).to(DEVICE)

    with torch.no_grad():

        logits = model(
            tensor
        )

        probabilities = torch.sigmoid(
            logits
        )[0].cpu().numpy()

    results = []

    for index, probability in enumerate(
        probabilities
    ):

        results.append({

            "index": index,

            "condition":
                disease_labels[index],

            "probability":
                float(probability)

        })

    results.sort(
        key=lambda x: x["probability"],
        reverse=True
    )

    session_results = results

    text = """
# 🧠 AI Screening Result

### Detected retinal conditions / abnormalities

"""

    for result in results[:10]:

        percentage = (
            result["probability"] * 100
        )

        text += (
            f"**{result['condition']}**  \n"
            f"Confidence: **{percentage:.2f}%**\n\n"
        )

    text += """
---

### ⚠️ Screening Notice

This result is generated by an AI screening model.
It is **not a medical diagnosis** and should be
reviewed by a qualified eye-care professional.
"""

    return text


# ============================================================
# 10. GRAD-CAM
# ============================================================

def generate_gradcam(image):

    if image is None:
        return None

    if not session_results:
        return None

    target_index = session_results[0]["index"]

    model.eval()

    img = image.convert("RGB")

    tensor = transform(
        img
    ).unsqueeze(0).to(DEVICE)

    activations = []
    gradients = []

    target_layer = model.features[-1]

    def forward_hook(
        module,
        input,
        output
    ):

        activations.append(
            output
        )

    def backward_hook(
        module,
        grad_input,
        grad_output
    ):

        gradients.append(
            grad_output[0]
        )

    forward_handle = (
        target_layer.register_forward_hook(
            forward_hook
        )
    )

    backward_handle = (
        target_layer.register_full_backward_hook(
            backward_hook
        )
    )

    try:

        output = model(
            tensor
        )

        target_score = output[
            0,
            target_index
        ]

        model.zero_grad()

        target_score.backward()

        activation = (
            activations[0].detach()
        )

        gradient = (
            gradients[0].detach()
        )

        weights = gradient.mean(
            dim=(2, 3),
            keepdim=True
        )

        cam = (
            weights * activation
        ).sum(dim=1)

        cam = F.relu(
            cam
        )

        cam = (
            cam[0]
            .cpu()
            .numpy()
        )

        if cam.max() > 0:

            cam = (
                cam / cam.max()
            )

        original = np.array(
            img
        )

        import cv2

        heatmap = cv2.resize(

            cam,

            (
                original.shape[1],
                original.shape[0]
            )
        )

        heatmap = np.uint8(
            255 * heatmap
        )

        heatmap = cv2.applyColorMap(

            heatmap,

            cv2.COLORMAP_JET
        )

        heatmap = cv2.cvtColor(

            heatmap,

            cv2.COLOR_BGR2RGB
        )

        overlay = (

            0.55 * original
            +
            0.45 * heatmap

        ).clip(
            0,
            255
        ).astype(
            np.uint8
        )

        # Label the two panels

        import PIL.ImageDraw as ImageDraw
        import PIL.ImageFont as ImageFont

        combined = np.hstack(
            [
                original,
                overlay
            ]
        )

        result_image = Image.fromarray(
            combined
        )

        return result_image

    finally:

        forward_handle.remove()
        backward_handle.remove()


# ============================================================
# 11. PATIENT INFORMATION
# ============================================================

def save_patient(
    name,
    age,
    gender,
    diabetes,
    symptoms
):

    global patient_data

    patient_data = {

        "name": name,

        "age": age,

        "gender": gender,

        "diabetes": diabetes,

        "symptoms": symptoms
    }

    return (
        "✅ Patient information saved."
    )


# ============================================================
# 12. REPORT
# ============================================================

def generate_report():

    if not session_results:

        return """
## 📄 Screening Report

No screening result available yet.
"""

    report = """
# 📄 RETINAGUARD Screening Report

### Patient Information

"""

    if patient_data:

        report += (
            f"**Name:** {patient_data.get('name','-')}  \n"
            f"**Age:** {patient_data.get('age','-')}  \n"
            f"**Gender:** {patient_data.get('gender','-')}  \n"
            f"**Diabetes Duration:** {patient_data.get('diabetes','-')}  \n"
            f"**Symptoms Duration:** {patient_data.get('symptoms','-')}  \n\n"
        )

    report += """
---

### AI Screening Findings

"""

    for result in session_results[:10]:

        report += (
            f"- **{result['condition']}** — "
            f"{result['probability']*100:.2f}%\n"
        )

    report += """

---

### Recommendation

The screening result should be reviewed by a
qualified eye-care professional.

Do not make treatment decisions based only on
this AI screening result.

### Medical Notice

RETINAGUARD is an AI screening aid and does not
replace professional eye examination.
"""

    return report


# ============================================================
# 13. PAGE NAVIGATION
# ============================================================

def show_page(number):

    return [

        gr.update(
            visible=(number == 0)
        ),

        gr.update(
            visible=(number == 1)
        ),

        gr.update(
            visible=(number == 2)
        ),

        gr.update(
            visible=(number == 3)
        ),

        gr.update(
            visible=(number == 4)
        ),

        gr.update(
            visible=(number == 5)
        ),

        gr.update(
            visible=(number == 6)
        ),

        gr.update(
            visible=(number == 7)
        )
    ]


# ============================================================
# 14. CSS
# ============================================================

css = """

body {

    background:
        #061426;

}

.gradio-container {

    max-width:
        1200px !important;

    margin:
        auto !important;

    background:
        linear-gradient(
            135deg,
            #061426,
            #0a2038
        );

}

button {

    border-radius:
        12px !important;

}

.gr-button-primary {

    background:
        linear-gradient(
            90deg,
            #087ea4,
            #13b8a6
        ) !important;

    color:
        white !important;

    border:
        none !important;

}

"""


# ============================================================
# 15. COMPLETE WEBSITE
# ============================================================

with gr.Blocks(

    title=
        "RETINAGUARD – Explainable AI",

    css=css

) as connected_app:


    # --------------------------------------------------------
    # PAGE 0 - WELCOME
    # --------------------------------------------------------

    with gr.Column(
        visible=True
    ) as page0:

        gr.Markdown("""

# 👁️ RETINAGUARD

## Explainable AI for Rural Retinal Screening

### AI-powered retinal screening with visual explanations

---

### 🔬 Intelligent retinal analysis
### 🧠 Explainable AI
### 🌾 Designed for accessible rural screening

""")

        start_button = gr.Button(

            "🚀 Start RETINAGUARD",

            variant="primary"
        )


    # --------------------------------------------------------
    # PAGE 1 - SIGN IN
    # --------------------------------------------------------

    with gr.Column(
        visible=False
    ) as page1:

        gr.Markdown("""

# 🔐 Sign In

### Access RETINAGUARD Screening

""")

        login_email = gr.Textbox(
            label="Email"
        )

        login_password = gr.Textbox(
            label="Password",
            type="password"
        )

        login_button = gr.Button(

            "Sign In →",

            variant="primary"
        )


    # --------------------------------------------------------
    # PAGE 2 - PATIENT
    # --------------------------------------------------------

    with gr.Column(
        visible=False
    ) as page2:

        gr.Markdown("""

# 👤 Patient Information

Enter basic patient information before screening.

""")

        patient_name = gr.Textbox(
            label="Full Name"
        )

        patient_age = gr.Number(
            label="Age"
        )

        patient_gender = gr.Dropdown(

            [
                "Male",
                "Female",
                "Other"
            ],

            label="Gender"
        )

        diabetes_duration = gr.Number(

            label=
                "Diabetes Duration (years)"
        )

        symptom_duration = gr.Number(

            label=
                "Symptoms Duration (days)"
        )

        patient_status = gr.Markdown()

        patient_continue = gr.Button(

            "Continue to Retina Screening →",

            variant="primary"
        )


    # --------------------------------------------------------
    # PAGE 3 - SCREENING
    # --------------------------------------------------------

    with gr.Column(
        visible=False
    ) as page3:

        gr.Markdown("""

# 📷 Retina Screening

### Capture or upload a retinal / fundus image

""")

        retina_image = gr.Image(

            sources=[
                "upload",
                "webcam"
            ],

            type="pil",

            label=
                "📷 Retinal / Fundus Image"
        )

        screen_button = gr.Button(

            "🔍 Start AI Screening",

            variant="primary"
        )

        screening_status = gr.Markdown()

        screening_next = gr.Button(

            "View AI Result →"
        )


    # --------------------------------------------------------
    # PAGE 4 - RESULT
    # --------------------------------------------------------

    with gr.Column(
        visible=False
    ) as page4:

        gr.Markdown(
            "# 🧠 AI Screening Result"
        )

        result_output = gr.Markdown()

        result_continue = gr.Button(

            "Continue to Explainable AI →",

            variant="primary"
        )


    # --------------------------------------------------------
    # PAGE 5 - EXPLAINABLE AI
    # --------------------------------------------------------

    with gr.Column(
        visible=False
    ) as page5:

        gr.Markdown("""

# 🔬 Explainable AI

### Grad-CAM Visual Explanation

The heatmap highlights image regions that influenced
the AI model's prediction.

**Red / Yellow:** higher model attention
**Blue:** lower model attention

""")

        gradcam_button = gr.Button(

            "🔥 Generate AI Explanation",

            variant="primary"
        )

        gradcam_output = gr.Image(

            label=
                "Original Image + AI Attention Heatmap"
        )

        explain_continue = gr.Button(

            "View Recommendation →",

            variant="primary"
        )


    # --------------------------------------------------------
    # PAGE 6 - RECOMMENDATION
    # --------------------------------------------------------

    with gr.Column(
        visible=False
    ) as page6:

        gr.Markdown("""

# 💡 Screening Recommendation

### Recommended Next Steps

- Discuss the screening result with a qualified eye-care professional.
- Further clinical examination may be required.
- Do not make treatment decisions based only on this AI result.
- Use the AI result as a screening support tool.

---

### ⚠️ Important

RETINAGUARD is an AI screening aid,
not a medical diagnosis.

""")

        recommendation_continue = gr.Button(

            "Generate Screening Report →",

            variant="primary"
        )


    # --------------------------------------------------------
    # PAGE 7 - REPORT + HISTORY
    # --------------------------------------------------------

    with gr.Column(
        visible=False
    ) as page7:

        gr.Markdown(
            "# 📄 Screening Report"
        )

        report_output = gr.Markdown()

        report_button = gr.Button(

            "🔄 Refresh Report",

            variant="primary"
        )

        gr.Markdown("""

---

# 📋 Screening History

### Current Screening Session

✅ Patient information recorded
✅ Retinal image screened
✅ AI result generated
✅ Explainable AI analysis generated
✅ Recommendation generated

""")

        restart_button = gr.Button(

            "🏠 Back to Home"
        )


    pages = [

        page0,
        page1,
        page2,
        page3,
        page4,
        page5,
        page6,
        page7
    ]


    # ========================================================
    # BUTTON ACTIONS
    # ========================================================

    start_button.click(

        lambda:
            show_page(1),

        outputs=pages
    )


    login_button.click(

        lambda:
            show_page(2),

        outputs=pages
    )


    patient_continue.click(

        save_patient,

        inputs=[

            patient_name,
            patient_age,
            patient_gender,
            diabetes_duration,
            symptom_duration

        ],

        outputs=patient_status

    ).then(

        lambda:
            show_page(3),

        outputs=pages
    )


    screen_button.click(

        predict_retina,

        inputs=retina_image,

        outputs=screening_status

    )


    screening_next.click(

        lambda:
            show_page(4),

        outputs=pages
    )


    result_continue.click(

        lambda:
            show_page(5),

        outputs=pages
    )


    gradcam_button.click(

        generate_gradcam,

        inputs=retina_image,

        outputs=gradcam_output
    )


    explain_continue.click(

        lambda:
            show_page(6),

        outputs=pages
    )


    recommendation_continue.click(

        generate_report,

        outputs=report_output

    ).then(

        lambda:
            show_page(7),

        outputs=pages
    )


    report_button.click(

        generate_report,

        outputs=report_output
    )


    restart_button.click(

        lambda:
            show_page(0),

        outputs=pages
    )


# ============================================================
# 16. LAUNCH WEB PAGE
# ============================================================

print("")
print("==========================================")
print("🚀 RETINAGUARD WEB PAGE READY")
print("==========================================")
print("")

connected_app.launch(
    share=True,
    debug=True
)

# Save RETINAGUARD app code
